apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deploy 
  labels:
    app: nodejs
spec:
  replicas: 10
  selector:
    matchLabels:
      app: nodejs
 
  template:
    metadata:
      labels:
        app: nodejs 
    spec:
      terminationGracePeriodSeconds: 1
      containers:
      - name: hello-pod 
        image: nodejs-app
        imagePullPolicy: Never
        ports:
        - containerPort: 3000

    
 
